services:
  h1:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
    - subnet_1
    environment:
    - CONNECTED_TO=R1
    - WEIGHT_TO_ROUTER=4
  h2:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
    - subnet_1
    environment:
    - CONNECTED_TO=R1
    - WEIGHT_TO_ROUTER=4
  r1:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
    - subnet_1
    - inter_router_r1_r2
    - inter_router_r1_r3
    environment:
    - CONNECTED_TO_SUBNET=subnet_1
    - CONNECTED_TO_ROUTER_R2=8
    - CONNECTED_TO_ROUTER_R3=4
  h3:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
    - subnet_2
    environment:
    - CONNECTED_TO=R2
    - WEIGHT_TO_ROUTER=5
  h4:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
    - subnet_2
    environment:
    - CONNECTED_TO=R2
    - WEIGHT_TO_ROUTER=1
  r2:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
    - subnet_2
    - inter_router_r1_r2
    - inter_router_r2_r3
    environment:
    - CONNECTED_TO_SUBNET=subnet_2
    - CONNECTED_TO_ROUTER_R1=8
    - CONNECTED_TO_ROUTER_R3=8
  h5:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
    - subnet_3
    environment:
    - CONNECTED_TO=R3
    - WEIGHT_TO_ROUTER=4
  h6:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
    - subnet_3
    environment:
    - CONNECTED_TO=R3
    - WEIGHT_TO_ROUTER=5
  r3:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
    - subnet_3
    - inter_router_r1_r3
    - inter_router_r2_r3
    environment:
    - CONNECTED_TO_SUBNET=subnet_3
    - CONNECTED_TO_ROUTER_R1=4
    - CONNECTED_TO_ROUTER_R2=8
networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.1.0/24
  subnet_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.2.0/24
  subnet_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.3.0/24
  inter_router_r1_r2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.1.0/24
  inter_router_r1_r3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.2.0/24
  inter_router_r2_r3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.21.3.0/24
