services:
  r1:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: r1
    environment:
      CONTAINER_NAME: r1
      CONNECTED_TO_ROUTER_r1: '9'
    volumes:
    - ./shared:/app
    networks:
      r1_r2_net:
        ipv4_address: 10.10.1.2
      r1_r5_net:
        ipv4_address: 10.10.2.2
      r1_hosts_net:
        ipv4_address: 192.168.7.2
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.send_redirects=0
  h1:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h1
    networks:
      r1_hosts_net:
        ipv4_address: 192.168.7.3
    environment:
    - CONNECTED_TO=R1
    - CONTAINER_NAME=h1
    - GATEWAY_IP=192.168.7.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  h2:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h2
    networks:
      r1_hosts_net:
        ipv4_address: 192.168.7.4
    environment:
    - CONNECTED_TO=R1
    - CONTAINER_NAME=h2
    - GATEWAY_IP=192.168.7.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  r2:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: r2
    environment:
      CONTAINER_NAME: r2
      CONNECTED_TO_ROUTER_r1: '4'
      CONNECTED_TO_ROUTER_r2: '3'
    volumes:
    - ./shared:/app
    networks:
      r1_r2_net:
        ipv4_address: 10.10.1.3
      r2_r3_net:
        ipv4_address: 10.10.3.2
      r2_hosts_net:
        ipv4_address: 192.168.8.2
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.send_redirects=0
  h3:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h3
    networks:
      r2_hosts_net:
        ipv4_address: 192.168.8.3
    environment:
    - CONNECTED_TO=R2
    - CONTAINER_NAME=h3
    - GATEWAY_IP=192.168.8.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  h4:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h4
    networks:
      r2_hosts_net:
        ipv4_address: 192.168.8.4
    environment:
    - CONNECTED_TO=R2
    - CONTAINER_NAME=h4
    - GATEWAY_IP=192.168.8.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  r3:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: r3
    environment:
      CONTAINER_NAME: r3
      CONNECTED_TO_ROUTER_r2: '3'
      CONNECTED_TO_ROUTER_r3: '1'
    volumes:
    - ./shared:/app
    networks:
      r2_r3_net:
        ipv4_address: 10.10.3.3
      r3_r4_net:
        ipv4_address: 10.10.4.2
      r3_r5_net:
        ipv4_address: 10.10.5.2
      r3_hosts_net:
        ipv4_address: 192.168.9.2
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.send_redirects=0
  h5:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h5
    networks:
      r3_hosts_net:
        ipv4_address: 192.168.9.3
    environment:
    - CONNECTED_TO=R3
    - CONTAINER_NAME=h5
    - GATEWAY_IP=192.168.9.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  h6:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h6
    networks:
      r3_hosts_net:
        ipv4_address: 192.168.9.4
    environment:
    - CONNECTED_TO=R3
    - CONTAINER_NAME=h6
    - GATEWAY_IP=192.168.9.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  r4:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: r4
    environment:
      CONTAINER_NAME: r4
      CONNECTED_TO_ROUTER_r3: '7'
      CONNECTED_TO_ROUTER_r4: '9'
    volumes:
    - ./shared:/app
    networks:
      r3_r4_net:
        ipv4_address: 10.10.4.3
      r4_r5_net:
        ipv4_address: 10.10.6.2
      r4_hosts_net:
        ipv4_address: 192.168.10.2
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.send_redirects=0
  h7:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h7
    networks:
      r4_hosts_net:
        ipv4_address: 192.168.10.3
    environment:
    - CONNECTED_TO=R4
    - CONTAINER_NAME=h7
    - GATEWAY_IP=192.168.10.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  h8:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h8
    networks:
      r4_hosts_net:
        ipv4_address: 192.168.10.4
    environment:
    - CONNECTED_TO=R4
    - CONTAINER_NAME=h8
    - GATEWAY_IP=192.168.10.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  r5:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: r5
    environment:
      CONTAINER_NAME: r5
      CONNECTED_TO_ROUTER_r1: '9'
      CONNECTED_TO_ROUTER_r3: '1'
      CONNECTED_TO_ROUTER_r4: '9'
    volumes:
    - ./shared:/app
    networks:
      r1_r5_net:
        ipv4_address: 10.10.2.3
      r3_r5_net:
        ipv4_address: 10.10.5.3
      r4_r5_net:
        ipv4_address: 10.10.6.3
      r5_hosts_net:
        ipv4_address: 192.168.11.2
    cap_add:
    - NET_ADMIN
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.accept_redirects=0
    - net.ipv4.conf.all.send_redirects=0
  h9:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h9
    networks:
      r5_hosts_net:
        ipv4_address: 192.168.11.3
    environment:
    - CONNECTED_TO=R5
    - CONTAINER_NAME=h9
    - GATEWAY_IP=192.168.11.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
  h10:
    build:
      context: .
      dockerfile: host/Dockerfile
    container_name: h10
    networks:
      r5_hosts_net:
        ipv4_address: 192.168.11.4
    environment:
    - CONNECTED_TO=R5
    - CONTAINER_NAME=h10
    - GATEWAY_IP=192.168.11.2
    cap_add:
    - NET_ADMIN
    volumes:
    - ./shared:/app
networks:
  r1_r2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.1.0/24
  r1_r5_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.2.0/24
  r2_r3_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.3.0/24
  r3_r4_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.4.0/24
  r3_r5_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.5.0/24
  r4_r5_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.6.0/24
  r1_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.7.0/24
  r2_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.8.0/24
  r3_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.9.0/24
  r4_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.10.0/24
  r5_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.11.0/24
