version: '3.8'
services:
  h1_1:
    image: busybox
    networks:
      subnet1:
        ipv4_address: 192.168.1.2
    command: sh -c "ip route add default via 192.168.1.1 && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
  h1_2:
    image: busybox
    networks:
      subnet1:
        ipv4_address: 192.168.1.3
    command: sh -c "ip route add default via 192.168.1.1 && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
  h2_1:
    image: busybox
    networks:
      subnet2:
        ipv4_address: 192.168.2.2
    command: sh -c "ip route add default via 192.168.2.1 && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
  h2_2:
    image: busybox
    networks:
      subnet2:
        ipv4_address: 192.168.2.3
    command: sh -c "ip route add default via 192.168.2.1 && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
  h3_1:
    image: busybox
    networks:
      subnet3:
        ipv4_address: 192.168.3.2
    command: sh -c "ip route add default via 192.168.3.1 && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
  h3_2:
    image: busybox
    networks:
      subnet3:
        ipv4_address: 192.168.3.3
    command: sh -c "ip route add default via 192.168.3.1 && tail -f /dev/null"
    cap_add:
      - NET_ADMIN
  r1:
    build: .
    networks:
      subnet1:
        ipv4_address: 192.168.1.1
      link1_2:
        ipv4_address: 10.0.1.1
    cap_add:
      - NET_ADMIN
    command: python router.py --id r1 --subnet 192.168.1.0/24 --link 10.0.1.0/24
    sysctls:
      - net.ipv4.ip_forward=1
  r2:
    build: .
    networks:
      subnet2:
        ipv4_address: 192.168.2.1
      link1_2:
        ipv4_address: 10.0.1.2
      link2_3:
        ipv4_address: 10.0.2.1
    cap_add:
      - NET_ADMIN
    command: python router.py --id r2 --subnet 192.168.2.0/24 --link 10.0.1.0/24 --link 10.0.2.0/24
    sysctls:
      - net.ipv4.ip_forward=1
  r3:
    build: .
    networks:
      subnet3:
        ipv4_address: 192.168.3.1
      link2_3:
        ipv4_address: 10.0.2.2
    cap_add:
      - NET_ADMIN
    command: python router.py --id r3 --subnet 192.168.3.0/24 --link 10.0.2.0/24
    sysctls:
      - net.ipv4.ip_forward=1

networks:
  subnet1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  subnet2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
  subnet3:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24
  link1_2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  link2_3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
